
spring:
  application:
    name: ${APPLICATION_NAME:SPENDING_MANAGEMENT_SERVICE}
  profiles:
    active:
      - dev
      - dev-local
  liquibase:
    change-log: classpath:db/master.xml
application:
  token:
    key: shopsport@2023
    expire-time-access-token: 86400000
    expire-time-refresh-token: 86400000
    logging:
      level:
        root: DEBUG